[package]
name = "stock_algo"
version = "0.1.0"
edition = "2021"

[lib]
name = "py_connect"
crate-type = ["cdylib"]

[dependencies]
csv = "1.3.0"
pyo3 = { version = "0.21.2", features = ["extension-module"] }
